### ISSUE TITLE
understand resolve_collision approach

### ISSUE THREAD

**Issue by qsh-zh** [erwincoumans/pyrigidbody3d#1]
Thanks for the simple and clean repo. 

TinyDifferentialSimulator repo and the paper, like Interactive Simulation of Rigid Body Dynamics in Computer Graphics, really help me understand simulators a lot. 

I have the question for the calculation for contact force, in this toy repo:
```python
  if cp.distance < 0:
    baumgarte_rel_vel = erp * cp.distance / dt
  rel_vel = cp.body_a.get_velocity(rel_posA) - cp.body_b.get_velocity(rel_posB)
  normal_rel_vel = cp.world_normal_on_b.dot(rel_vel)
  if normal_rel_vel < 0.0:
    temp1 = cp.body_a.inv_inertia_world.dot(
        np.cross(rel_posA, cp.world_normal_on_b))
    temp2 = cp.body_b.inv_inertia_world.dot(
        np.cross(rel_posB, cp.world_normal_on_b))
    ang = cp.world_normal_on_b.dot(
        np.cross(temp1, rel_posA) + np.cross(temp2, rel_posB))
    impulse = (-(1.0 + cp.body_b.restitution) * normal_rel_vel -
               baumgarte_rel_vel) / (
                   cp.body_a.inv_mass + cp.body_b.inv_mass + ang)
    if impulse > 0:
```

Why do we need the variable `ang` when calculating the impulse, does this term have a physical meaning? (The thesis link has broken, is there an intuitive explanation for calculation?)

**Comment by erwincoumans** [comment]
If a collision happens, there can be a linear effect (motion of the center of mass) and 'ang' a rotational effect (rotating around the center of mass).
![image](https://user-images.githubusercontent.com/725468/138203412-7147c1bc-8088-457c-acfb-fdf9ac3515c3.png)
